import type { Metadata } from "next";
import {
  sans,
  sansMedium,
  sansBold,
  sansItalic,
  sansSemiboldItalic,
} from "@/fonts/font";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "antialiased",
        "font-sans",
        sans.variable,
        sansMedium.variable,
        sansBold.variable,
        sansItalic.variable,
        sansSemiboldItalic.variable,
      )}
      suppressHydrationWarning
    >
      <body className="relative p-4 flex flex-col">
        <TooltipProvider>
          <Navbar />
          <main className="min-h-screen">{children}</main>
          <Footer />
        </TooltipProvider>
      </body>
    </html>
  );
}
